### ISSUE TITLE
Next Page of Freelancers

### ISSUE THREAD

**Issue by imnvr** [madvas/ethlance#17]
If I enter the site for the first time (without being logged in) and I click on "find candidates" and then go to next page without specifying a skill it says "no more candidates are available".

**Comment by madvas** [comment]
This sometimes happens with MetaMask for unknown reason. After refreshing page or re-enabling MetaMask it usually starts to work normally. Never happens with Mist or Parity. So this is MetaMask issue, not Ethlance. If this persists to you, please let me know.

**Comment by imnvr** [comment]
I did not have metamask installed when I tried this

**Comment by madvas** [comment]
hmm, so what were you using, just plain browser without MetaMask?

**Comment by imnvr** [comment]
Correct.
