### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by imnvr** [madvas/ethlance#18]
Where can we see how many users ethlance has ?

**Comment by madvas** [comment]
We currently don't display this info anywhere. Is there some specific reason why you need this?

**Comment by imnvr** [comment]
Out of pure interest about the project really, no other reason.

**Comment by madvas** [comment]
318 registered users at the moment 😉

**Comment by imnvr** [comment]
Do you think it would help to display this somewhere or not ?

**Comment by madvas** [comment]
I don't think right now it'd be very helpful, but we'll see in the future

**Comment by imnvr** [comment]
I've read in an article that you have a plan to capture 4% of the freelancing jobs this year or something like that. How do you plan to promote the platform and do that ?

**Comment by madvas** [comment]
Well, first we plan to develop genuinely better product than current freelance platforms. We should be able to do this thanks to Ethereum enabling us to have new features like: sponsored jobs, payments in any token, smart-contract based escrows, zero fees etc. We'll have ICO to help raise funds for all this development. Of course some resources will be used for marketing, but we want to focus on creating best product in the first place.
