### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by tjayrush** [madvas/ethlance#4]
The site is excellent, not a single complaint. I used it to post a job.

I was just thinking, before this thing takes off and everyone knows who you are (because that will happen), you should change the name of the site. eth-anything is starting to get really old, and it will soon sound very old-fashioned. Branch out to a name that doesn't have the word 'eth' in it. I'm pretty sure you'll be glad you did.

You can close this issue if you want. It's just a suggestion.

**Comment by madvas** [comment]
Hi, thank you very much! 
As for the name, it's not the first time I've met with this opinion. I will give it a thought.
Just to put out some arguments against: 
- There's many Bit* services for bitcoin and it seems kinda working. 
- ethlance refers to well known service elance, but payments are in Ether. I think there's no reason to try to hide that. 

but yea, I'm open to other suggestions, nothing is set in stone
