### ISSUE TITLE
Interest in the deploy

### ISSUE THREAD

**Issue by ghosthamlet** [madvas/ethlance#5]
Hi madvas, can you show the deploy workflow on Ethereum public blockchain and  IPFS, i think the automate deploy script may be very useful to others developing dapps.

**Comment by salsa-dev** [comment]
+1

**Comment by madvas** [comment]
Hey, sure. I don't have any super automated script, but I think it's fairly simple. 
Note: My way of deploying is very Clojure specific. If you're unfamiliar with Clojure ecosystem this won't make too much sense to you.
Here's some glossary
[lein](https://leiningen.org/)
[Clojurescript REPL](https://www.youtube.com/watch?v=KZjFVdU8VLI)

When I deploy to IPFS:
```
lein cljsbuild once min
ipfs add -r resources/public/
ipfs name publish [hash of "public" folder from previous command here]
```
When I want to deploy smart contract open ethlance with figwheel REPL running and just send this to Clojurescript REPL (this is specific to ethlance):
```clojure
; This will deploy all smart contracts again
(dispatch [:reintialize])
; This will deploy only a specific smart contract (EthlanceJob.sol)
(dispatch [:reintialize [:ethlance-job]])
; New addresses will be printed into console. Contract instances will be swapped in running app's re-frame db
```

**Comment by ghosthamlet** [comment]
Thanks. I get it. Your ethlance is very cool, i am also interest in and learning Clojure IPFS Ethereum too.
