### ISSUE TITLE
Can't upload my profile picture

### ISSUE THREAD

**Issue by ksahin** [madvas/ethlance#7]
Hi, 

I created a Freelancer profile, when I created the profile I couldn't change de default profile picture. 
I can't change it now when I click on the profile picture. 

Is it normal ?

**Comment by madvas** [comment]
Hi, for now we use [Gravatar](http://gravatar.com/) for profile picture. If you go to their website, associate some profile picture with your email. Then when you input your email on our site, we will be able to calculate URL for your gravatar profile picture without actually revealing your email. Many other websites use gravatar for their profile pics and it needs to be setup just once
