### ISSUE TITLE
"First name" calculation is slightly off

### ISSUE THREAD

**Issue by gnidan** [madvas/ethlance#8]
Not sure where all on the site freelancer names get abbreviated as first-name-only, but at least on the toolbar, it's a bit weird when I write my name formally as first letter of first name, full middle name:

<img width="822" alt="screen shot 2017-02-21 at 11 12 39" src="https://cloud.githubusercontent.com/assets/151065/23173378/f8b6fd00-f826-11e6-8f95-bff068fa303f.png">

Just a minor gribble though. Maybe it would make sense to take every word up until the last, rather than just the first word? Seeing `g. nicholas` everywhere instead of `g.` feels a bit less like a robot is trying to guess what to call me.

(Ideally, it'd be nice to have a separate field for "friendly name" or whatever, because, for instance, the name I use formally is not the same as the name I tell people to call me)

-Nick

**Comment by madvas** [comment]
yep, changed this to include every word, but the last one. Thanks for pointing this out
